// Session state for the board. Pure reducer, so the whole thing can be driven
// from a list of actions and nothing here depends on when it runs.
//
// Every clearance the operator has issued stays on the board for the session,
// including the closed ones. A conformance monitor whose history scrolls away
// is not much use to the person reviewing it.

import type { Aircraft, Clearance, Constraint, TrackSample } from './types.ts'
import { evaluate, isOpen, supersede } from './conform.ts'

/**
 * Samples retained per clearance. At a 2 s poll this is about eight minutes,
 * comfortably longer than the 120 s evaluation window and enough to draw a
 * trend line that shows the whole manoeuvre.
 */
export const MAX_HISTORY = 240

export type BoardState = {
  /** Newest first, so an amendment appears directly above what it replaced. */
  clearances: Clearance[]
}

export type BoardAction =
  /** The id and issuedAt are generated by the caller so this stays pure. */
  | { type: 'ISSUE'; clearance: Clearance }
  | { type: 'SNAPSHOT'; byHex: Map<string, Aircraft>; now: number }
  | { type: 'CLEAR' }

export const initialBoardState: BoardState = { clearances: [] }

/** Take the moving numbers off an aircraft; identity already lives on the clearance. */
export function toSample(a: Aircraft): TrackSample {
  return {
    ts: a.ts,
    altFt: a.altFt,
    vsFpm: a.vsFpm,
    gsKt: a.gsKt,
    trackTrue: a.trackTrue,
    navHeading: a.navHeading,
    seenPosSec: a.seenPosSec,
  }
}

/**
 * Append a sample, ignoring one we already have.
 *
 * The API route serves a cached snapshot for up to 1.5 s, so two polls can
 * return the same instant. Storing it twice would make an aircraft look like it
 * held altitude for a poll it never reported.
 */
function appendSample(history: TrackSample[], sample: TrackSample): TrackSample[] {
  const last = history[history.length - 1]
  if (last && last.ts === sample.ts) return history
  const next = [...history, sample]
  return next.length > MAX_HISTORY ? next.slice(next.length - MAX_HISTORY) : next
}

export function boardReducer(state: BoardState, action: BoardAction): BoardState {
  switch (action.type) {
    case 'ISSUE': {
      // Close anything this clearance amends before adding it, so the old one
      // is never left open to fail a window it can no longer meet.
      const closed = supersede(state.clearances, action.clearance)
      return { clearances: [action.clearance, ...closed] }
    }

    case 'SNAPSHOT': {
      const clearances = state.clearances.map((c) => {
        // A closed clearance keeps the evidence it was closed on. Re-judging it
        // against later behaviour would rewrite history every two seconds.
        if (!isOpen(c.status)) return c

        const ac = action.byHex.get(c.hex)
        const history = ac ? appendSample(c.history, toSample(ac)) : c.history
        const assessment = evaluate({ ...c, history }, history, action.now)
        if (history === c.history && assessment.verdict === c.status && assessment.detail === c.detail) {
          return c
        }
        return { ...c, history, status: assessment.verdict, detail: assessment.detail }
      })
      return { clearances }
    }

    case 'CLEAR':
      return initialBoardState
  }
}

/** Build a clearance. The id and timestamp come from the caller to keep this pure. */
export function makeClearance(args: {
  id: string
  issuedAt: number
  aircraft: Aircraft
  constraint: Constraint
  spokenText: string
  spokenCallsign: string
}): Clearance {
  return {
    id: args.id,
    hex: args.aircraft.hex,
    spokenText: args.spokenText,
    spokenCallsign: args.spokenCallsign,
    resolvedCallsign: args.aircraft.callsign ?? args.aircraft.registration ?? args.aircraft.hex,
    registration: args.aircraft.registration,
    constraint: args.constraint,
    issuedAt: args.issuedAt,
    status: 'PENDING',
    detail: 'issued, waiting for the first response',
    history: [toSample(args.aircraft)],
  }
}

/**
 * The series the trend line should plot for a clearance, and the value the
 * aircraft was told to reach. Each constraint is judged on a different number,
 * so each one plots that number rather than always plotting altitude.
 */
export function trendSeries(c: Clearance): { values: number[]; target: number; unit: string } | null {
  const samples = c.history
  switch (c.constraint.kind) {
    case 'ALTITUDE': {
      const values = samples.map((s) => s.altFt).filter((v): v is number => v !== null)
      return values.length ? { values, target: c.constraint.targetFt, unit: 'ft' } : null
    }
    case 'SPEED': {
      const values = samples.map((s) => s.gsKt).filter((v): v is number => v !== null)
      return values.length ? { values, target: c.constraint.targetKt, unit: 'kt' } : null
    }
    case 'HEADING': {
      // Headings are unwrapped before plotting: a turn from 350 through 010 is
      // a short continuous line, not a full height drop down the chart.
      const raw = samples
        .map((s) => (s.navHeading !== null ? s.navHeading : s.trackTrue !== null ? s.trackTrue - 13 : null))
        .filter((v): v is number => v !== null)
      if (!raw.length) return null
      const values = unwrapDegrees(raw)
      // Move the target onto the same unwrapped branch as the last plotted point.
      const last = values[values.length - 1]
      const target = last + shortestDelta(last, c.constraint.targetDegMag)
      return { values, target, unit: '°' }
    }
  }
}

/** Signed shortest difference, duplicated locally so this module stays presentational. */
function shortestDelta(from: number, to: number): number {
  return ((to - from + 540) % 360) - 180
}

/** Remove the 360 degree jumps from a heading series so it plots as a continuous line. */
function unwrapDegrees(series: number[]): number[] {
  const out = [series[0]]
  for (let i = 1; i < series.length; i++) {
    out.push(out[i - 1] + shortestDelta(series[i - 1], series[i]))
  }
  return out
}
