// Session state for the board. Pure reducer, so the whole thing can be driven
// from a list of actions and nothing here depends on when it runs.
//
// The bay holds the clearances still worth looking at. Amending an instruction
// replaces its strip rather than stacking a second one beside it, and closed
// strips retire on age, the way a physical rack gets cleared as traffic moves on.

import type { Aircraft, Clearance, Constraint, TrackSample } from './types.ts'
import { evaluate, isOpen } from './conform.ts'

/**
 * Samples retained per clearance. At a 2 s poll this is about eight minutes,
 * comfortably longer than the 120 s evaluation window and enough to draw a
 * trend line that shows the whole manoeuvre.
 */
export const MAX_HISTORY = 240

/**
 * How many strips the bay holds.
 *
 * A real bay is a rack and it holds what it holds. When it is full, closed
 * strips are pulled before open ones, oldest first.
 */
export const MAX_STRIPS = 8

/** A closed strip is pulled from the bay once it is this old. */
export const RETIRE_CLOSED_MS = 8 * 60 * 1000

export type BoardState = {
  /** Newest first, so an amendment appears directly above what it replaced. */
  clearances: Clearance[]
}

export type BoardAction =
  /** The id and issuedAt are generated by the caller so this stays pure. */
  | { type: 'ISSUE'; clearance: Clearance }
  | { type: 'SNAPSHOT'; byHex: Map<string, Aircraft>; now: number }
  | { type: 'CLEAR' }

export const initialBoardState: BoardState = { clearances: [] }

/** Take the moving numbers off an aircraft; identity already lives on the clearance. */
export function toSample(a: Aircraft): TrackSample {
  return {
    ts: a.ts,
    altFt: a.altFt,
    vsFpm: a.vsFpm,
    gsKt: a.gsKt,
    trackTrue: a.trackTrue,
    navHeading: a.navHeading,
    seenPosSec: a.seenPosSec,
  }
}

/**
 * Append a sample, ignoring one we already have.
 *
 * The API route serves a cached snapshot for up to 1.5 s, so two polls can
 * return the same instant. Storing it twice would make an aircraft look like it
 * held altitude for a poll it never reported.
 */
function appendSample(history: TrackSample[], sample: TrackSample): TrackSample[] {
  const last = history[history.length - 1]
  if (last && last.ts === sample.ts) return history
  const next = [...history, sample]
  return next.length > MAX_HISTORY ? next.slice(next.length - MAX_HISTORY) : next
}

export function boardReducer(state: BoardState, action: BoardAction): BoardState {
  switch (action.type) {
    case 'ISSUE': {
      // One strip per aircraft. Any earlier clearance to the same aircraft is
      // pulled from the bay and the new one takes its place at the top.
      //
      // Matching on hex alone, not on hex and constraint kind. The engine's
      // supersede() is narrower on purpose: a speed assignment genuinely does
      // not cancel an altitude assignment, and it stays that way. But the bay
      // is a rack a person reads at a glance, and two strips for one callsign
      // is two things to reconcile mid sentence. Whatever was last said to this
      // aircraft is what the strip shows.
      //
      // Status is deliberately not consulted. An earlier clearance that already
      // went DEVIATED is still an earlier clearance, and leaving it behind was
      // exactly how "alaska 236 descend 5000" then "alaska 236 descend 3000"
      // ended up as two strips.
      const previous = state.clearances.filter((c) => c.hex === action.clearance.hex)
      const others = state.clearances.filter((c) => c.hex !== action.clearance.hex)

      // Carry the most recent previous strip's track forward so the trend line
      // does not restart from nothing, and keep what it used to say.
      const last = previous.sort((a, b) => a.issuedAt - b.issuedAt).pop()
      const issued: Clearance = last
        ? {
            ...action.clearance,
            amendedFrom: last.constraint,
            history:
              last.history.length > action.clearance.history.length
                ? last.history
                : action.clearance.history,
          }
        : action.clearance

      return { clearances: prune([issued, ...others], action.clearance.issuedAt) }
    }

    case 'SNAPSHOT': {
      const clearances = state.clearances.map((c) => {
        // A closed clearance keeps the evidence it was closed on. Re-judging it
        // against later behaviour would rewrite history every two seconds.
        if (!isOpen(c.status)) return c

        const ac = action.byHex.get(c.hex)
        const history = ac ? appendSample(c.history, toSample(ac)) : c.history
        const assessment = evaluate({ ...c, history }, history, action.now)
        if (history === c.history && assessment.verdict === c.status && assessment.detail === c.detail) {
          return c
        }
        return { ...c, history, status: assessment.verdict, detail: assessment.detail }
      })
      return { clearances: prune(clearances, action.now) }
    }

    case 'CLEAR':
      return initialBoardState
  }
}

/**
 * Keep the bay to a workable size.
 *
 * A physical strip bay is a rack and it holds what it holds. Closed strips
 * retire on age first, then the rack is trimmed to MAX_STRIPS: closed strips go
 * before open ones, and within each group the oldest goes first. The cap is
 * hard, because COMPLYING and COMPLIED are both still "open" and a bay that
 * only ever drops closed strips is a bay that grows without limit.
 *
 * Display order is always newest first, whatever the drop order was.
 */
function prune(clearances: Clearance[], now: number): Clearance[] {
  const fresh = clearances.filter((c) => isOpen(c.status) || now - c.issuedAt < RETIRE_CLOSED_MS)
  if (fresh.length <= MAX_STRIPS) return [...fresh].sort((a, b) => b.issuedAt - a.issuedAt)

  const ranked = [...fresh].sort((a, b) => {
    const aOpen = isOpen(a.status) ? 0 : 1
    const bOpen = isOpen(b.status) ? 0 : 1
    if (aOpen !== bOpen) return aOpen - bOpen
    return b.issuedAt - a.issuedAt
  })
  const kept = new Set(ranked.slice(0, MAX_STRIPS))
  return fresh.filter((c) => kept.has(c)).sort((a, b) => b.issuedAt - a.issuedAt)
}

/** Build a clearance. The id and timestamp come from the caller to keep this pure. */
export function makeClearance(args: {
  id: string
  issuedAt: number
  aircraft: Aircraft
  constraint: Constraint
  spokenText: string
  spokenCallsign: string
}): Clearance {
  return {
    id: args.id,
    hex: args.aircraft.hex,
    spokenText: args.spokenText,
    spokenCallsign: args.spokenCallsign,
    resolvedCallsign: args.aircraft.callsign ?? args.aircraft.registration ?? args.aircraft.hex,
    registration: args.aircraft.registration,
    constraint: args.constraint,
    issuedAt: args.issuedAt,
    status: 'PENDING',
    detail: 'issued, waiting for the first response',
    history: [toSample(args.aircraft)],
    amendedFrom: null,
  }
}

/**
 * The series the trend line should plot for a clearance, and the value the
 * aircraft was told to reach. Each constraint is judged on a different number,
 * so each one plots that number rather than always plotting altitude.
 */
export function trendSeries(c: Clearance): { values: number[]; target: number; unit: string } | null {
  const samples = c.history
  switch (c.constraint.kind) {
    case 'ALTITUDE': {
      const values = samples.map((s) => s.altFt).filter((v): v is number => v !== null)
      return values.length ? { values, target: c.constraint.targetFt, unit: 'ft' } : null
    }
    case 'SPEED': {
      const values = samples.map((s) => s.gsKt).filter((v): v is number => v !== null)
      return values.length ? { values, target: c.constraint.targetKt, unit: 'kt' } : null
    }
    case 'HEADING': {
      // Headings are unwrapped before plotting: a turn from 350 through 010 is
      // a short continuous line, not a full height drop down the chart.
      const raw = samples
        .map((s) => (s.navHeading !== null ? s.navHeading : s.trackTrue !== null ? s.trackTrue - 13 : null))
        .filter((v): v is number => v !== null)
      if (!raw.length) return null
      const values = unwrapDegrees(raw)
      // Move the target onto the same unwrapped branch as the last plotted point.
      const last = values[values.length - 1]
      const target = last + shortestDelta(last, c.constraint.targetDegMag)
      return { values, target, unit: '°' }
    }
  }
}

/** Signed shortest difference, duplicated locally so this module stays presentational. */
function shortestDelta(from: number, to: number): number {
  return ((to - from + 540) % 360) - 180
}

/** Remove the 360 degree jumps from a heading series so it plots as a continuous line. */
function unwrapDegrees(series: number[]): number[] {
  const out = [series[0]]
  for (let i = 1; i < series.length; i++) {
    out.push(out[i - 1] + shortestDelta(series[i - 1], series[i]))
  }
  return out
}
